name: lint ansible playbook

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          args: "-v --project-dir ."

      # - name: Install ansible-lint from system packages
      #   run: |
      #     sudo apt update
      #     sudo apt install ansible-core ansible-lint

      - name: Install ansible-lint with pip
        run: |
          sudo apt update
          sudo apt install pip git
          pip install ansible-core ansible-lint

      - name: Run ansible-lint on our repo
        run: |
          ansible-galaxy collection install -r requirements.yml
          ansible-lint -v -s --project-dir .
