name: lint ansible playbook

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # current: 6.22.1, working: v6.11.0 (?)
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.11.0
        with:
          args: "-v"
